# Generated by Django 5.0.1 on 2024-01-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('imgs', models.ImageField(upload_to='mypic')),
                ('description', models.TextField()),
            ],
        ),
    ]
